export const siteConfig = {
  name: "Ads House",
  legalName: "Ads House",
  tagline: "Growth. By Design.",
  description:
    "Ads House (adshouse.in) is a digital marketing and ads agency in Rohtak, Haryana. SEO, Google Ads, Meta ads, branding, websites, and software for Indian brands.",
  url: "https://www.adshouse.in",
  domain: "adshouse.in",
  locale: "en_IN",
  language: "en-IN",
  email: "info.adshouse@gmail.com",
  phone: "+91 8708892875",
  phoneHref: "tel:+918708892875",
  whatsapp: "https://wa.me/918708892875",
  foundingYear: 2026,
  alternateNames: [
    "Adshouse",
    "AdsHouse",
    "ads house",
    "Ads House Agency",
    "adshouse.in",
    "Ads House Rohtak",
    "Ads House ads agency",
    "Ads House digital marketing",
  ],
  address: {
    street: "",
    locality: "Rohtak",
    region: "Haryana",
    postalCode: "124001",
    country: "IN",
    countryName: "India",
  },
  geo: {
    latitude: 28.8955,
    longitude: 76.6066,
  },
  hours: {
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] as const,
    opens: "10:00",
    closes: "19:00",
    timezone: "Asia/Kolkata",
  },
  social: {
    instagram: "https://www.instagram.com/adshouse.in/",
    linkedin: "https://www.linkedin.com/company/ads_house",
    x: "https://x.com/adshouserohtak",
    threads: "https://www.threads.com/@adshouse.in",
    youtube: "https://www.youtube.com/@adshouse",
  },
  twitterHandle: "@adshouserohtak",
  cities: ["Rohtak"],
  keywords: [
    "Ads House",
    "adshouse",
    "ads house",
    "adshouse.in",
    "ads house agency",
    "ads agency in Rohtak",
    "adshouse ads agency",
    "digital marketing ads house",
    "digital marketing agency in Rohtak",
    "advertising agency Rohtak",
    "SEO agency Rohtak",
    "Google Ads agency Rohtak",
    "Meta ads agency Rohtak",
    "digital marketing company Haryana",
    "performance marketing agency India",
  ],
} as const;

export const defaultTitle = "Ads House | Ads Agency in Rohtak | Digital Marketing";

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/work", label: "Work" },
  { href: "/locations", label: "Office" },
  { href: "/about", label: "About" },
  { href: "/insights", label: "Insights" },
  { href: "/contact", label: "Contact" },
] as const;
