export const siteConfig = {
  name: "Ads House",
  legalName: "Ads House",
  tagline: "Growth. By Design.",
  description:
    "Ads House is a full-service digital marketing and advertising agency in India. We build brands, launch high-performing campaigns, and engineer websites and software that turn attention into revenue.",
  url: "https://www.adshouse.in",
  locale: "en_IN",
  language: "en-IN",
  email: "info.adshouse@gmail.com",
  phone: "+91 8708892875",
  phoneHref: "tel:+918708892875",
  whatsapp: "https://wa.me/918708892875",
  foundingYear: 2018,
  address: {
    street: "",
    locality: "Rohtak",
    region: "Haryana",
    postalCode: "",
    country: "IN",
    countryName: "India",
  },
  geo: {
    latitude: 28.8955,
    longitude: 76.6066,
  },
  social: {
    instagram: "https://www.instagram.com/adshouse",
    linkedin: "https://www.linkedin.com/company/adshouse",
    x: "https://x.com/adshouse",
    youtube: "https://www.youtube.com/@adshouse",
  },
  cities: [
    "Rohtak",
    "Delhi NCR",
    "Mumbai",
    "Bengaluru",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Ahmedabad",
    "Kolkata",
  ],
  keywords: [
    "digital marketing agency India",
    "advertising agency Mumbai",
    "performance marketing agency India",
    "brand building agency",
    "best digital marketing company in India",
    "SEO agency India",
    "social media marketing agency",
    "website development company India",
    "custom software development agency",
    "D2C marketing agency",
    "Google Ads agency India",
    "Meta ads agency",
    "growth marketing agency India",
  ],
} as const;

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/work", label: "Work" },
  { href: "/about", label: "About" },
  { href: "/insights", label: "Insights" },
  { href: "/contact", label: "Contact" },
] as const;
