export const siteConfig = {
  name: "Ads House",
  legalName: "Ads House",
  tagline: "Growth. By Design.",
  description:
    "Ads House is a digital marketing and advertising agency in Rohtak, Haryana, serving brands across India. SEO, Google Ads, Meta ads, branding, websites, and software that turn attention into revenue.",
  url: "https://www.adshouse.in",
  locale: "en_IN",
  language: "en-IN",
  email: "info.adshouse@gmail.com",
  phone: "+91 8708892875",
  phoneHref: "tel:+918708892875",
  whatsapp: "https://wa.me/918708892875",
  foundingYear: 2018,
  address: {
    street: "",
    locality: "Rohtak",
    region: "Haryana",
    postalCode: "124001",
    country: "IN",
    countryName: "India",
  },
  geo: {
    latitude: 28.8955,
    longitude: 76.6066,
  },
  hours: {
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] as const,
    opens: "10:00",
    closes: "19:00",
    timezone: "Asia/Kolkata",
  },
  social: {
    instagram: "https://www.instagram.com/adshouse.in/",
    linkedin: "https://www.linkedin.com/company/ads_house",
    x: "https://x.com/adshouserohtak",
    threads: "https://www.threads.com/@adshouse.in",
    youtube: "https://www.youtube.com/@adshouse",
  },
  twitterHandle: "@adshouserohtak",
  cities: [
    "Rohtak",
    "Delhi NCR",
    "Mumbai",
    "Bengaluru",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Ahmedabad",
    "Kolkata",
  ],
  keywords: [
    "digital marketing agency in Rohtak",
    "digital marketing agency India",
    "advertising agency Rohtak",
    "SEO agency Rohtak",
    "SEO agency India",
    "Google Ads agency India",
    "performance marketing agency India",
    "brand building agency India",
    "website development company India",
    "Meta ads agency",
    "digital marketing company Haryana",
    "growth marketing agency India",
    "D2C marketing agency",
    "social media marketing agency India",
  ],
} as const;

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/work", label: "Work" },
  { href: "/locations", label: "Locations" },
  { href: "/about", label: "About" },
  { href: "/insights", label: "Insights" },
  { href: "/contact", label: "Contact" },
] as const;
